### ISSUE TITLE
Drop yaml-cpp-0.3 formula

### ISSUE THREAD

**Issue by mikepurvis** [ros/homebrew-deps#15]
Upstream is 0.5.3: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yaml-cpp.rb

Trusty's version is 0.5.1: http://packages.ubuntu.com/source/trusty/yaml-cpp

Was 0.3 supporting Hydro? If so, that can certainly be dropped at this point.

**Comment by wjwwood** [comment]
@mikepurvis you'd have to change the rosdep key: https://github.com/ros/rosdistro/blob/be98bc9ad5d275d1e6016adbcd675c044bb02f8e/rosdep/osx-homebrew.yaml#L732-L736

Once you do that, everyone will start using the upstream `0.5` version of `yaml-cpp`, and so removing this will not be necessary. In light of that, I'll close this. Feel free to continue the discussion and I reopen if necessary.

**Comment by mikepurvis** [comment]
Done: https://github.com/ros/rosdistro/pull/11287
